In [1]:
from mxnet import nd
import mxnet as mx

In [2]:
!set MXNET_GLUON_REPO=https://apache-mxnet.s3.cn-north-1.amazonaws.com.cn/ jupyter notebook

In [25]:
x = nd.arange(20, ctx=mx.gpu())

In [26]:
X = x.reshape((3,4))

创建矩阵

In [16]:
array = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

arange = nd.arange(20).reshape((4,5))

ones = nd.ones((3,3,3))

zeros = nd.zeros((2,3))

full = nd.full((2,3), 2)

random_normal = nd.random.normal(0,1, shape=(12,))

random_randn = nd.random.randn(2,3)

random_randint = nd.random.randint(1, 10, shape=(2, 3))  # 通过shape指定形状

运算, 元素运算：加减乘除

In [18]:
random_randn + full


[[0.5774245 1.4823802 4.0088325]
 [2.2863085 2.5604596 2.9697597]]
<NDArray 2x3 @cpu(0)>

In [19]:
random_randn - full


[[-3.4225755  -2.5176198   0.00883245]
 [-1.7136915  -1.4395405  -1.0302403 ]]
<NDArray 2x3 @cpu(0)>

In [20]:
random_randn * full


[[-2.845151  -1.0352398  4.017665 ]
 [ 0.572617   1.120919   1.9395195]]
<NDArray 2x3 @cpu(0)>

In [21]:
random_randn / full


[[-0.71128774 -0.25880995  1.0044162 ]
 [ 0.14315425  0.28022975  0.48487988]]
<NDArray 2x3 @cpu(0)>

矩阵乘法

In [22]:
nd.dot(random_randn, full.T)


[[0.13727427 0.13727427]
 [3.6330557  3.6330557 ]]
<NDArray 2x2 @cpu(0)>

asscalar函数将结果变换为Python中的标量

In [23]:
random_randn.mean().asscalar()

0.31419417

索引 前面冒号是行的切片，后面的冒号的列的切片，列的切片可以省略，行的不可以

In [25]:
arange[:,:]  


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
<NDArray 4x5 @cpu(0)>

In [26]:
arange[1:3]


[[ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
<NDArray 2x5 @cpu(0)>

In [27]:
arange[:,1:3]


[[ 1.  2.]
 [ 6.  7.]
 [11. 12.]
 [16. 17.]]
<NDArray 4x2 @cpu(0)>

In [31]:
arange.take(nd.array([0,3]))


[[ 0.  1.  2.  3.  4.]
 [15. 16. 17. 18. 19.]]
<NDArray 2x5 @cpu(0)>

赋值

In [32]:
arange[0,0] = 100

In [34]:
arange[:, 1:2] = 200

In [35]:
arange


[[100. 200.   2.   3.   4.]
 [  5. 200.   7.   8.   9.]
 [ 10. 200.  12.  13.  14.]
 [ 15. 200.  17.  18.  19.]]
<NDArray 4x5 @cpu(0)>

NDArray和Numpy转换

In [36]:
import numpy as np

In [39]:
# numpy 转 nd
np_array = np.ones((2,3))
nd_array = nd.array(np_array)

In [40]:
# nd 转 np
np_array = nd_array.asnumpy()

使用gpu

In [41]:
import mxnet as mx

是否有gpu可以使用

In [43]:
mx.context.num_gpus()  # 获取gpu数量， 0就是没有

1

In [45]:
nd.ones((3,3), ctx=mx.gpu())


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @gpu(0)>

cpu,gpu转换

In [48]:
zeros.as_in_context(mx.gpu())
zeros.copyto(mx.cpu())


[[0. 0. 0.]
 [0. 0. 0.]]
<NDArray 2x3 @cpu(0)>